# makefile.config
#   
#   Dave William/DNE
#   dave.williams.github@gmail.com
#

TARGET_ARCH     := linux64
SYSTEMC_HOME    := /650GB/Downloads/SystemC_2_3_3/systemc-2.3.3/

# setup SYSTEMC_HOME and TARGET_ARCH in your environment
SYSTEMC_INC_DIR  := $(SYSTEMC_HOME)/include
SYSTEMC_LIB_DIR  := $(SYSTEMC_HOME)/lib64-$(TARGET_ARCH)

