#target name  
TARGET		:= rv32
TARGET_NAME  	:= $(TARGET)im

#project paths
PROJECT_PATH    := /home/dave/MyProjects/RiscV
#TOOL_PATH	:= $(PROJECT_PATH)/$(TARGET)/riscv-tools/riscv/bin
TOOL_PATH	:= $(PROJECT_PATH)/$(TARGET)/riscv-tools/riscv/bin

#build type
BUILD_NAME	:= riscv32-unknown-elf

#assembler/linker paths
ASM_PATH	:= $(PROJECT_PATH)/rv64/asm
#ASM_SOURCES	:= $(wildcard $(ASM_PATH)/src/*.s)
ASM_SOURCES	:= src/$(TARGET_NAME).s
LINK_SCRIPT 	:= $(ASM_PATH)/link/link

#outputs
OUTPUT_PATH 	:= $(ASM_PATH)/output
OBJS 		:= $(OUTPUT_PATH)/$(TARGET_NAME).o
OUT_LST 	:= $(OUTPUT_PATH)/$(TARGET_NAME).lst

#script
SCRIPT_PROCESS	:= $(ASM_PATH)/scripts/main

#binutils
ASM		:= $(TOOL_PATH)/$(BUILD_NAME)-as
LINK		:= $(TOOL_PATH)/$(BUILD_NAME)-ld
OBJDUMP		:= $(TOOL_PATH)/$(BUILD_NAME)-objdump
OBJCOPY		:= $(TOOL_PATH)/$(BUILD_NAME)-objcopy
GCC_RV		:= $(TOOL_PATH)/$(BUILD_NAME)-gcc
STRIP		:= $(TOOL_PATH)/$(BUILD_NAME)-strip
READELF		:= $(TOOL_PATH)/$(BUILD_NAME)-readelf
